/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package interfaz;

import blockbuster.Director;
import blockbuster.Function;
import blockbuster.Genre;
import java.awt.Color;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class NewMovie extends javax.swing.JInternalFrame {
//    private String[] errors = {"","","",""};

    private PrincipalPanel parent;

    /**
     * Creates new form NewMovie
     *
     * @param parent
     */
    
    //New movie class constructor
    public NewMovie(PrincipalPanel parent) {
        initComponents();
        this.parent = parent;
        updateDirectors();
        updateGenres();
//        btnSaveMovie.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        tfTitle = new javax.swing.JTextField();
        lblGenre = new javax.swing.JLabel();
        tfYear = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSaveMovie = new javax.swing.JButton();
        btnAddDirector = new javax.swing.JButton();
        genreList = new java.awt.List();
        cmbxDirector = new javax.swing.JComboBox<>();
        btnCancelMovie = new javax.swing.JButton();
        tfUnits = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);

        lblTitle.setText("Title: ");

        tfTitle.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                tfTitleInputMethodTextChanged(evt);
            }
        });
        tfTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTitleActionPerformed(evt);
            }
        });
        tfTitle.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tfTitlePropertyChange(evt);
            }
        });
        tfTitle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfTitleKeyTyped(evt);
            }
        });

        lblGenre.setText("Genre:");

        tfYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfYearActionPerformed(evt);
            }
        });
        tfYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfYearKeyTyped(evt);
            }
        });

        jLabel1.setText("Year:");

        jLabel2.setText("Director:");

        btnSaveMovie.setText("Save");
        btnSaveMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveMovieActionPerformed(evt);
            }
        });

        btnAddDirector.setText("Add director");
        btnAddDirector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDirectorActionPerformed(evt);
            }
        });

        genreList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genreListActionPerformed(evt);
            }
        });

        cmbxDirector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnCancelMovie.setText("Cancel");
        btnCancelMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelMovieActionPerformed(evt);
            }
        });

        tfUnits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUnitsActionPerformed(evt);
            }
        });
        tfUnits.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfUnitsKeyTyped(evt);
            }
        });

        jLabel3.setText("Units");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbxDirector, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAddDirector))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfUnits, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(lblGenre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGap(4, 4, 4)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(genreList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tfYear, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(btnSaveMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnCancelMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, lblGenre, lblTitle});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmbxDirector, genreList, tfTitle, tfUnits, tfYear});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancelMovie, btnSaveMovie});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfYear, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfUnits, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genreList, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbxDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddDirector))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, lblGenre, lblTitle});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cmbxDirector, tfTitle, tfYear});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCancelMovie, btnSaveMovie});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfYearActionPerformed
    
    //It is responsible for adding movies to its respective list
    private void btnSaveMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveMovieActionPerformed
        // TODO add your handling code here:
        String movieTitle = tfTitle.getText();
        String units = tfUnits.getText();
        String[] genres = genreList.getSelectedItems();
        Object director = cmbxDirector.getSelectedItem();
        String year = tfYear.getText();
        int indexDirectorSelected = cmbxDirector.getSelectedIndex();
        String error = "";
        boolean validYear = Function.validateInt(year, 1885, 2024);
        boolean validUnits = Function.validateInt(units, 0, 9999);
        if (!validYear) {
            error += "Enter a valid number in the year field\n";
        }
        if (!validUnits) {
            error += "Enter a valid number in the units field\n";
        }
        if (movieTitle.equals("")
                || year.equals("")
                || units.equals("")
                || genres.length == 0
                || (director == null || indexDirectorSelected == 0)) {
            error += "You must fill out all the fields";
        }
        if (!error.equals("")) {
            JOptionPane.showMessageDialog(null, error);
        } else {
            parent.getBlockBuster().saveMovie(movieTitle, genres, year, director, units);
            JOptionPane.showMessageDialog(null, "Movie saved successfully");
            setEmpty();
        }
    }//GEN-LAST:event_btnSaveMovieActionPerformed

    private void tfTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTitleActionPerformed

    //It is responsible for adding directors to its respective list
    private void btnAddDirectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDirectorActionPerformed
        // TODO add your handling code here:
        NewDirector newDirector = new NewDirector(this, this.parent);
        newDirector.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAddDirectorActionPerformed

    //Responsible for displaying and updating the directors list
    public void updateDirectors() {
        Vector<Director> directorsCopy = new Vector<>(parent.getBlockBuster().getDirectors());
        DefaultComboBoxModel defaultComboBoxModel = new DefaultComboBoxModel(directorsCopy);
        defaultComboBoxModel.insertElementAt("------Select an option------", 0);
        cmbxDirector.setModel(defaultComboBoxModel);
        cmbxDirector.setSelectedIndex(0);
    }
    
    //Responsible for updating the directors list
    public void updateGenres(){
        Vector<Genre> genres = parent.getBlockBuster().getGenres();
        for (Genre genre : genres) {
            genreList.add(genre.toString());
        }
        genreList.setMultipleMode(true);
    }
    private void genreListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genreListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genreListActionPerformed

    private void tfTitlePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tfTitlePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTitlePropertyChange

    private void tfTitleInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tfTitleInputMethodTextChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_tfTitleInputMethodTextChanged

    private void tfTitleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTitleKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTitleKeyTyped

    private void tfYearKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfYearKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tfYearKeyTyped

    //Closes the window 
    private void btnCancelMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelMovieActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        setEmpty();
    }//GEN-LAST:event_btnCancelMovieActionPerformed

    private void tfUnitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUnitsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUnitsActionPerformed

    private void tfUnitsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfUnitsKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUnitsKeyTyped
    
    //Getter
    public JComboBox<String> getCmbxDirector() {
        return cmbxDirector;
    }
    
    //Clears the information window to its default mode
    private void setEmpty() {
        tfTitle.setText("");
        tfYear.setText("");
        tfUnits.setText("");
        cmbxDirector.setSelectedIndex(0);
        int[] selectedGenreIndexes = genreList.getSelectedIndexes();
        for (int index : selectedGenreIndexes) {
            genreList.deselect(index);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDirector;
    private javax.swing.JButton btnCancelMovie;
    private javax.swing.JButton btnSaveMovie;
    private javax.swing.JComboBox<String> cmbxDirector;
    private java.awt.List genreList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblGenre;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField tfTitle;
    private javax.swing.JTextField tfUnits;
    private javax.swing.JTextField tfYear;
    // End of variables declaration//GEN-END:variables
}
