/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package interfaz;

import blockbuster.BlockBuster;

/**
 *
 * @author USER
 */

public class PrincipalPanel extends javax.swing.JFrame {

    private NewMovie newMovie = null;
    private NewClient newClient = null;
    private MovieInventory movieInventory = null;
    private ClientList clientList = null;
    private NewRent newRent = null;
    private BlockBuster blockBuster = new BlockBuster();
    private ShowRentals showRentals = null;

    public BlockBuster getBlockBuster() {
        return blockBuster;
    }

    /**
     * Creates new form PrincipalPanel
     */
    
    //PrincipalPanel class constructor 
    public PrincipalPanel() {
        initComponents();
        blockBuster.fill();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        menuArchive = new javax.swing.JMenu();
        btnNewMovie = new javax.swing.JMenuItem();
        btnNewClient = new javax.swing.JMenuItem();
        btnExitPrincipal = new javax.swing.JMenuItem();
        menuView = new javax.swing.JMenu();
        btnMovieInventory = new javax.swing.JMenuItem();
        btnClientList = new javax.swing.JMenuItem();
        menuRent = new javax.swing.JMenu();
        btnNewRent = new javax.swing.JMenuItem();
        btnShowRentals = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuArchive.setMnemonic('f');
        menuArchive.setText("File");

        btnNewMovie.setMnemonic('o');
        btnNewMovie.setText("New Movie");
        btnNewMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewMovieActionPerformed(evt);
            }
        });
        menuArchive.add(btnNewMovie);

        btnNewClient.setMnemonic('s');
        btnNewClient.setText("New Customer");
        btnNewClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewClientActionPerformed(evt);
            }
        });
        menuArchive.add(btnNewClient);

        btnExitPrincipal.setMnemonic('x');
        btnExitPrincipal.setText("Exit");
        btnExitPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitPrincipalActionPerformed(evt);
            }
        });
        menuArchive.add(btnExitPrincipal);

        menuBar.add(menuArchive);

        menuView.setMnemonic('e');
        menuView.setText("View");

        btnMovieInventory.setMnemonic('t');
        btnMovieInventory.setText("Movies Inventory");
        btnMovieInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovieInventoryActionPerformed(evt);
            }
        });
        menuView.add(btnMovieInventory);

        btnClientList.setMnemonic('y');
        btnClientList.setText("Customer List");
        btnClientList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientListActionPerformed(evt);
            }
        });
        menuView.add(btnClientList);

        menuBar.add(menuView);

        menuRent.setMnemonic('h');
        menuRent.setText("Rental");

        btnNewRent.setMnemonic('c');
        btnNewRent.setText("New rental");
        btnNewRent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewRentActionPerformed(evt);
            }
        });
        menuRent.add(btnNewRent);

        btnShowRentals.setMnemonic('a');
        btnShowRentals.setText("Show rentals");
        btnShowRentals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowRentalsActionPerformed(evt);
            }
        });
        menuRent.add(btnShowRentals);

        menuBar.add(menuRent);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 999, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitPrincipalActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitPrincipalActionPerformed

    //FIRST MENU Archives  

    private void btnNewMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewMovieActionPerformed
        // TODO add your handling code here:
        if (this.newMovie == null || this.newMovie.isClosed()) {
            this.newMovie = new NewMovie(this);
            this.desktopPane.add(this.newMovie);
        }
        this.newMovie.setVisible(true);
    }//GEN-LAST:event_btnNewMovieActionPerformed

    private void btnNewClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewClientActionPerformed
        // TODO add your handling code here:
        if (this.newClient == null || this.newClient.isClosed()) {
            this.newClient = new NewClient(this);
            this.desktopPane.add(this.newClient);
        }

        this.newClient.setVisible(true);
    }//GEN-LAST:event_btnNewClientActionPerformed

    //SECOND MENU View

    private void btnMovieInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovieInventoryActionPerformed
        // TODO add your handling code here:
        if (this.movieInventory == null || this.movieInventory.isClosed()) {
            this.movieInventory = new MovieInventory(this);
            this.desktopPane.add(this.movieInventory);
        }

        this.movieInventory.setVisible(true);
    }//GEN-LAST:event_btnMovieInventoryActionPerformed

    private void btnClientListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientListActionPerformed
        // TODO add your handling code here:
        if (this.clientList == null || this.clientList.isClosed()) {
            this.clientList = new ClientList(this);
            this.desktopPane.add(this.clientList);
        }

        this.clientList.setVisible(true);
    }//GEN-LAST:event_btnClientListActionPerformed

    // THIRD MENU Rent

    private void btnNewRentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewRentActionPerformed
        // TODO add your handling code here:
        if (this.newRent == null || this.newRent.isClosed()) {
            this.newRent = new NewRent(this);
            this.desktopPane.add(this.newRent);
        }

        this.newRent.setVisible(true);
    }//GEN-LAST:event_btnNewRentActionPerformed

    private void btnShowRentalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowRentalsActionPerformed
        // TODO add your handling code here:
        if (showRentals == null || this.showRentals.isClosed()) {
            showRentals = new ShowRentals(this);
            this.desktopPane.add(showRentals);
        }

        this.showRentals.setVisible(true);
    }//GEN-LAST:event_btnShowRentalsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnClientList;
    private javax.swing.JMenuItem btnExitPrincipal;
    private javax.swing.JMenuItem btnMovieInventory;
    private javax.swing.JMenuItem btnNewClient;
    private javax.swing.JMenuItem btnNewMovie;
    private javax.swing.JMenuItem btnNewRent;
    private javax.swing.JMenuItem btnShowRentals;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu menuArchive;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuRent;
    private javax.swing.JMenu menuView;
    // End of variables declaration//GEN-END:variables

}
