/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package proyectpoo;

/**
 *
 * @author USER
 */
public class JFBlockbuster extends javax.swing.JFrame {
    
    private JFArchive jfArchive = null; 
    private JFView jfView = null;
    private JFRent jfRent = null; 

    /**
     * Creates new form JFBlockbuster
     */
    public JFBlockbuster() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        ArchiveMenuItem = new javax.swing.JMenuItem();
        ViewMenuItem = new javax.swing.JMenuItem();
        RentMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Blockbuster");

        ArchiveMenuItem.setMnemonic('o');
        ArchiveMenuItem.setText("Archive");
        ArchiveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArchiveMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(ArchiveMenuItem);

        ViewMenuItem.setMnemonic('s');
        ViewMenuItem.setText("View");
        ViewMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(ViewMenuItem);

        RentMenuItem.setMnemonic('a');
        RentMenuItem.setText("Rent");
        RentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RentMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(RentMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void ArchiveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArchiveMenuItemActionPerformed
        // TODO add your handling code here:
        if(this.jfArchive == null || this.jfArchive.isClosed()){
            this.jfArchive = new JFArchive();
        }
        
        this.desktopPane.add(this.jfArchive);
        this.jfArchive.setVisible(true);
    }//GEN-LAST:event_ArchiveMenuItemActionPerformed

    private void ViewMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewMenuItemActionPerformed
        // TODO add your handling code here:
        if(this.jfView == null || this.jfView.isClosed()){
            this.jfView = new JFView();
        }
        
        this.desktopPane.add(this.jfView);
        this.jfView.setVisible(true);
    }//GEN-LAST:event_ViewMenuItemActionPerformed

    private void RentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RentMenuItemActionPerformed
        // TODO add your handling code here:
        if(this.jfRent == null || this.jfRent.isClosed()){
            this.jfRent = new JFRent();
        }
        
        this.desktopPane.add(this.jfRent);
        this.jfRent.setVisible(true);
    }//GEN-LAST:event_RentMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFBlockbuster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFBlockbuster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFBlockbuster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFBlockbuster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFBlockbuster().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ArchiveMenuItem;
    private javax.swing.JMenuItem RentMenuItem;
    private javax.swing.JMenuItem ViewMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
