/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package proyectpoo;

/**
 *
 * @author USER
 */
public class JFRent extends javax.swing.JInternalFrame {

    /**
     * Creates new form JFAlquileres
     */
    public JFRent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNewRent = new javax.swing.JButton();
        btnReturnRent = new javax.swing.JButton();

        btnNewRent.setText("New Rent");
        btnNewRent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewRentActionPerformed(evt);
            }
        });

        btnReturnRent.setText("Return");
        btnReturnRent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnRentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnNewRent, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(btnReturnRent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(btnNewRent)
                .addGap(42, 42, 42)
                .addComponent(btnReturnRent)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewRentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewRentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNewRentActionPerformed

    private void btnReturnRentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnRentActionPerformed
        // TODO add your handling code here:
        this.getParent().setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_btnReturnRentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNewRent;
    private javax.swing.JButton btnReturnRent;
    // End of variables declaration//GEN-END:variables
}
